apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: demo-app-email-alert
  namespace: monitoring
  labels:
    release: monitoring
spec:
  route:
    receiver: personal-email
    groupBy:
      - alertname
      - service
    groupWait: 10s
    groupInterval: 1m
    repeatInterval: 30m
    matchers:
      - name: alertname
        matchType: =
        value: DemoAppHighErrorRate

  receivers:
    - name: personal-email
      emailConfigs:
        - to: "bapn839@gmail.com"
          from: "bapn839@gmail.com"
          smarthost: "smtp.gmail.com:587"
          authUsername: "bapn839@gmail.com"
          authIdentity: "bapn839@gmail.com"
          authPassword:
            name: alertmanager-email-secret
            key: password
          requireTLS: true
          sendResolved: true