apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: demo-app-error-rate
  namespace: demo
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  metrics:
    - name: demo-app-5xx-count
      interval: 20s
      count: 3
      failureLimit: 1
      successCondition: result[0] == 0
      provider:
        prometheus:
          address: http://monitoring-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090
          query: |
            sum(
              increase(
                demo_http_requests_total{
                  namespace="demo",
                  status_code=~"5.."
                }[2m]
              )
            ) or vector(0)