apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  namespace: demo
  labels:
    app: demo-app
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - name: backend
          image: truonganngo/w8-w9-demo-backend:6151384
          ports:
            - containerPort: 5000
          env:
            - name: APP_VERSION
              value: "6151384"
          envFrom:
            - configMapRef:
                name: demo-app-config

        - name: frontend
          image: truonganngo/w8-w9-demo-frontend:6151384
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: demo-app-config