apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: demo-app
  namespace: demo
  labels:
    app: demo-app
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  replicas: 2
  strategy:
    canary:
      steps:
        - setWeight: 25
<<<<<<< HEAD
        - pause: 
            duration: 30s
=======
        - pause:
            duration: 30s
        - analysis:
            templates:
              - templateName: demo-app-error-rate
>>>>>>> parent of 0da32da (inject errors for email alert)
        - setWeight: 50
        - pause:
            duration: 30s
        - setWeight: 100

  selector:
    matchLabels:
      app: demo-app

  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - name: backend
          image: truonganngo/w8-w9-demo-backend:bb7f62b
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
          env:
            - name: APP_VERSION
              value: "v4-bad"
            - name: ERROR_RATE
              value: "1"
          envFrom:
            - configMapRef:
                name: demo-app-config

        - name: frontend
          image: truonganngo/w8-w9-demo-frontend:bb7f62b
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"
          envFrom:
            - configMapRef:
                name: demo-app-config